# Use exact Node.js version with glibc (not Alpine)
FROM node:18.19.1-bullseye-slim

# Set the working directory in the container
WORKDIR /app

# Copy ONLY package.json (ignore lockfile)
COPY package.json .
RUN rm -rf node_modules && \
    npm install --force --include=optional

# Copy the rest of the application files into the container
COPY . .

# Expose port 3000 for the development server
EXPOSE 3000

# Run the Vue.js development server
CMD ["npm", "run", "dev"]
