version: '3.8'

services:
  # Development override for the Backend API service
  driya.platform:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./DRIYA.Platform:/app  # Mount the backend source code for live updates
    command: ["dotnet", "watch", "run"]

  # Development override for the Frontend service
  driya.platformui:
    build:
      context: ./driya.platformui
      dockerfile: Dockerfile.dev   # Tell it to use the development Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080  # Backend API endpoint for development
    ports:
      - "3000:3000"
    volumes:
      - ./driya.platformui:/app  # Enable live reloading by binding the source
      - /app/node_modules  # Prevent host/node_modules conflicts- 
      - /app/.npm          # Cache directory
    command: ["npm", "run", "dev"]

  # (Optional) SQL Server override for development, if desired:
  # sqlserver:
  #   environment:
  #     SA_PASSWORD: YourStrong@Passw0rd
  #     MSSQL_PID: Express
  #   volumes:
  #     - ./sqlserver-dev-data:/var/opt/mssql

  # (Optional) Redis override for development, if additional logging is needed:
  # redis:
  #   command: ["redis-server", "--loglevel", "debug"]
  
# volumes:
#   sqlserver_data:
