version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: driya_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: driya_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: driya_redis
    ports:
      - "6379:6379" # Default Redis port
    command: ["redis-server"] # Default Redis command; no configuration needed for basic use

volumes:
  postgres_data: