version: '3.8'

services:
  # Backend API service (ASP.NET Core)
  driya.platform:
    image: ${DOCKER_REGISTRY:-}driyaplatform
    build:
      context: .
      dockerfile: DRIYA.Platform/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__SQLServerConnection=Server=sqlserver;Database=driya_db;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;MultipleActiveResultSets=true
      - Redis__ConnectionString=redis:6379
    ports:
      - "8080:8080" # HTTP port
      - "8081:8081" # HTTPS port (optional)
    depends_on:
      - sqlserver
      - redis

  # SQL Server database service
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: driya_sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong@Passw0rd
      MSSQL_PID: Express
    volumes:
      - sqlserver_data:/var/opt/mssql # Persistent volume for database data

  # Redis service
  redis:
    image: redis:latest
    container_name: driya_redis
    ports:
      - "6379:6379" # Default Redis port
    command: ["redis-server"]
    environment:
      - REDIS_LOG_LEVEL=notice # Set optional log level for Redis

volumes:
  sqlserver_data:
