version: '3.8'

services:
  # Development override for the Backend API service
  driya.platform:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./DRIYA.Platform:/app  # Mount the backend source code for live updates
    command: ["dotnet", "watch", "run"]


  # (Optional) SQL Server override for development, if desired:
  # sqlserver:
  #   environment:
  #     SA_PASSWORD: YourStrong@Passw0rd
  #     MSSQL_PID: Express
  #   volumes:
  #     - ./sqlserver-dev-data:/var/opt/mssql

  # (Optional) Redis override for development, if additional logging is needed:
  # redis:
  #   command: ["redis-server", "--loglevel", "debug"]
  
# volumes:
#   sqlserver_data:
