// <auto-generated />
using System;
using DRIYA.Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DRIYA.Platform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251005005605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastUsageReset")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonthlyUsage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Permissions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalUsage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKeyUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("int");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("Timestamp");

                    b.ToTable("ApiKeyUsage");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MfaSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemFeature")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureKey")
                        .IsUnique();

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a37e1b8-fdb7-435d-aecf-6115fdce8b14"),
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(3627),
                            DefaultValue = "true",
                            FeatureKey = "basic_analytics",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Basic Analytics"
                        },
                        new
                        {
                            Id = new Guid("db861713-9542-485a-a2c5-360fe77b1fdf"),
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(4334),
                            DefaultValue = "false",
                            FeatureKey = "advanced_analytics",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Advanced Analytics"
                        },
                        new
                        {
                            Id = new Guid("b5a75ae9-5dd2-4a57-a9b8-c8689b61978c"),
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(4338),
                            DefaultValue = "false",
                            FeatureKey = "custom_branding",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Custom Branding"
                        },
                        new
                        {
                            Id = new Guid("1a6b74ca-26f2-4cb6-9754-2e15327e527f"),
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(4340),
                            DefaultValue = "true",
                            FeatureKey = "api_access",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "API Access"
                        },
                        new
                        {
                            Id = new Guid("af0626f4-b2ab-4df5-afd4-8ad42e0ab077"),
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(4342),
                            DefaultValue = "false",
                            FeatureKey = "white_label",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "White Label"
                        },
                        new
                        {
                            Id = new Guid("cbe71b91-78cd-437b-baf5-8f523427074d"),
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(4351),
                            DefaultValue = "false",
                            FeatureKey = "priority_support",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Priority Support"
                        },
                        new
                        {
                            Id = new Guid("a9f94f1e-ff56-48b5-92e6-fa6ef0a85398"),
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(4352),
                            DefaultValue = "false",
                            FeatureKey = "sso_integration",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "SSO Integration"
                        },
                        new
                        {
                            Id = new Guid("5c4af8b1-64ca-405c-94bd-93fe437bd12b"),
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(4355),
                            DefaultValue = "false",
                            FeatureKey = "advanced_security",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Advanced Security"
                        });
                });

            modelBuilder.Entity("DRIYA.Platform.Models.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("bit");

                    b.Property<string>("OverrideBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("FeatureId", "TenantId", "UserId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL AND [UserId] IS NOT NULL");

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BillingPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BillingPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StripeInvoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.LicensePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowTrial")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemPlan")
                        .HasColumnType("bit");

                    b.Property<int>("MaxApiCalls")
                        .HasColumnType("int");

                    b.Property<int>("MaxStorageGB")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrialDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LicensePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea64641f-dc97-43a0-b28b-90fb5ac8367b"),
                            AllowTrial = true,
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(2542),
                            Currency = "USD",
                            Description = "Basic plan for small teams",
                            IsActive = true,
                            IsSystemPlan = true,
                            MaxApiCalls = 1000,
                            MaxStorageGB = 10,
                            MaxUsers = 5,
                            MonthlyPrice = 29.99m,
                            Name = "Basic",
                            PlanCode = "basic",
                            TrialDays = 14,
                            YearlyPrice = 299.99m
                        },
                        new
                        {
                            Id = new Guid("d0f16e34-e034-490f-9aec-1600d5ef3d76"),
                            AllowTrial = true,
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(2651),
                            Currency = "USD",
                            Description = "Professional plan for growing businesses",
                            IsActive = true,
                            IsSystemPlan = true,
                            MaxApiCalls = 10000,
                            MaxStorageGB = 100,
                            MaxUsers = 25,
                            MonthlyPrice = 99.99m,
                            Name = "Professional",
                            PlanCode = "pro",
                            TrialDays = 14,
                            YearlyPrice = 999.99m
                        },
                        new
                        {
                            Id = new Guid("0697f369-4ac9-44c2-a762-9a711f5fc9f5"),
                            AllowTrial = true,
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 81, DateTimeKind.Utc).AddTicks(2655),
                            Currency = "USD",
                            Description = "Premium plan for enterprise customers",
                            IsActive = true,
                            IsSystemPlan = true,
                            MaxApiCalls = 100000,
                            MaxStorageGB = 1000,
                            MaxUsers = 100,
                            MonthlyPrice = 299.99m,
                            Name = "Premium",
                            PlanCode = "premium",
                            TrialDays = 14,
                            YearlyPrice = 2999.99m
                        });
                });

            modelBuilder.Entity("DRIYA.Platform.Models.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistory");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PaymentGateway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GatewayType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTestMode")
                        .HasColumnType("bit");

                    b.Property<string>("MerchantId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SupportedCurrencies")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("SupportsBankTransfers")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsCreditCards")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsDigitalWallets")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsRecurringPayments")
                        .HasColumnType("bit");

                    b.Property<decimal>("TransactionFeeFixed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransactionFeePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("PaymentGateways");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GatewayFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("GatewayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GatewayId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TenantId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemPermission")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3870f6ea-a502-4aa5-8d28-a405d136b797"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8017),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "User Management",
                            Resource = "User"
                        },
                        new
                        {
                            Id = new Guid("f7c160b9-2138-4f74-b6c3-50eca1423528"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8858),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "User Management",
                            Resource = "User"
                        },
                        new
                        {
                            Id = new Guid("8de5754e-9b63-4ddf-9de2-0a6c756f6934"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8870),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "User Management",
                            Resource = "User"
                        },
                        new
                        {
                            Id = new Guid("7ec4d941-225b-4c6b-8e2e-9a7e64e47183"),
                            Action = "Delete",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8872),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "User Management",
                            Resource = "User"
                        },
                        new
                        {
                            Id = new Guid("fb38fa8e-940f-4046-b748-82ff293f33e0"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8874),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Tenant Management",
                            Resource = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("77ba2224-e6a1-4d5b-88d9-23b551c351a5"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8903),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Tenant Management",
                            Resource = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("1f82b577-a00a-42c0-af35-9a781e00e9fb"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8906),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Tenant Management",
                            Resource = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("8d79dd95-228f-4fac-bb70-591e31351178"),
                            Action = "Delete",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8908),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Tenant Management",
                            Resource = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("ac6cd512-1db7-4129-930c-841046ee2d6d"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8909),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Billing Management",
                            Resource = "Billing"
                        },
                        new
                        {
                            Id = new Guid("2c31d2ca-8211-4a42-a2d8-60f5b72a501b"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8912),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Billing Management",
                            Resource = "Billing"
                        },
                        new
                        {
                            Id = new Guid("acc83e75-9e4d-45ca-a5aa-8577a4f3007e"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8915),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Billing Management",
                            Resource = "Billing"
                        },
                        new
                        {
                            Id = new Guid("e7bb773f-1d47-46fb-9c72-fa64bb268c2a"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8938),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Feature Management",
                            Resource = "Feature"
                        },
                        new
                        {
                            Id = new Guid("01986367-0b38-438a-9f44-15eab7fdd50e"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8940),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Feature Management",
                            Resource = "Feature"
                        },
                        new
                        {
                            Id = new Guid("9ac9bb7e-8e91-41d7-a994-2df6de4bcd22"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8942),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Feature Management",
                            Resource = "Feature"
                        },
                        new
                        {
                            Id = new Guid("5b739450-06d5-4fd9-bea5-30fbda2217b7"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8945),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "API Key Management",
                            Resource = "ApiKey"
                        },
                        new
                        {
                            Id = new Guid("2f7d79a8-90ec-4b08-a69b-2db15bea8ac8"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8946),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "API Key Management",
                            Resource = "ApiKey"
                        },
                        new
                        {
                            Id = new Guid("1c79f572-eefb-4492-89b5-d5971db791ac"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8948),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "API Key Management",
                            Resource = "ApiKey"
                        },
                        new
                        {
                            Id = new Guid("47133edf-f7a0-4715-9150-098b5bf08a2d"),
                            Action = "Delete",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(8950),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "API Key Management",
                            Resource = "ApiKey"
                        });
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("Limit")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanFeatures");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParentRoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("ParentRoleId");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(1344),
                            Description = "Global system administrator with full access",
                            HierarchyLevel = 0,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "GlobalAdmin",
                            NormalizedName = "GLOBALADMIN"
                        },
                        new
                        {
                            Id = "2",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(1533),
                            Description = "Tenant administrator with full tenant access",
                            HierarchyLevel = 1,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "TenantAdmin",
                            NormalizedName = "TENANTADMIN"
                        },
                        new
                        {
                            Id = "3",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(1543),
                            Description = "Manager with limited administrative access",
                            HierarchyLevel = 2,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "4",
                            CreatedAt = new DateTime(2025, 10, 5, 0, 56, 5, 80, DateTimeKind.Utc).AddTicks(1553),
                            Description = "Standard user with basic access",
                            HierarchyLevel = 3,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("DRIYA.Platform.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrentPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrialActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactEmail");

                    b.HasIndex("CurrentPlanId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.TenantDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionString")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ConnectionTimeout")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Port")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseSSL")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantDatabases");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKey", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("ApiKeys")
                        .HasForeignKey("TenantId");

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKeyUsage", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApiKey", "ApiKey")
                        .WithMany("UsageHistory")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApplicationUser", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.FeatureFlag", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Feature", "Feature")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("TenantId");

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Feature");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Invoice", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.LicensePlan", "Plan")
                        .WithMany("Invoices")
                        .HasForeignKey("PlanId");

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("Invoices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.InvoiceItem", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.LoginHistory", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany("LoginHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PaymentTransaction", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.PaymentGateway", "Gateway")
                        .WithMany("Transactions")
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DRIYA.Platform.Models.Invoice", "Invoice")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gateway");

                    b.Navigation("Invoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PlanFeature", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Feature", "Feature")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.LicensePlan", "Plan")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Role", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Role", "ParentRole")
                        .WithMany("ChildRoles")
                        .HasForeignKey("ParentRoleId");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.RolePermission", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Tenant", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.LicensePlan", "CurrentPlan")
                        .WithMany("Tenants")
                        .HasForeignKey("CurrentPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentPlan");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.TenantDatabase", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("TenantDatabases")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.UserPermission", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.UserRole", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKey", b =>
                {
                    b.Navigation("UsageHistory");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApplicationUser", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("LoginHistory");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Feature", b =>
                {
                    b.Navigation("FeatureFlags");

                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.LicensePlan", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("PlanFeatures");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PaymentGateway", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Role", b =>
                {
                    b.Navigation("ChildRoles");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Tenant", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("FeatureFlags");

                    b.Navigation("Invoices");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("TenantDatabases");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
