// <auto-generated />
using System;
using DRIYA.Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DRIYA.Platform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastUsageReset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MonthlyUsage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Permissions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalUsage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKeyUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("Timestamp");

                    b.ToTable("ApiKeyUsage");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MfaSecretKey")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PhoneConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemFeature")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureKey")
                        .IsUnique();

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = new Guid("701c7074-9e3d-4537-a065-c1362c90851f"),
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(2171),
                            DefaultValue = "true",
                            FeatureKey = "basic_analytics",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Basic Analytics"
                        },
                        new
                        {
                            Id = new Guid("d13db1b4-d9aa-476a-8bc4-b131b7fe7897"),
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(2929),
                            DefaultValue = "false",
                            FeatureKey = "advanced_analytics",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Advanced Analytics"
                        },
                        new
                        {
                            Id = new Guid("49890f27-54f7-470a-9c04-d9d02bba86aa"),
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(2936),
                            DefaultValue = "false",
                            FeatureKey = "custom_branding",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Custom Branding"
                        },
                        new
                        {
                            Id = new Guid("5adedf80-a177-4954-876f-fb7214e0ce3f"),
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(2938),
                            DefaultValue = "true",
                            FeatureKey = "api_access",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "API Access"
                        },
                        new
                        {
                            Id = new Guid("3c11162f-cc9a-44a6-91e7-c2eff70ba9a8"),
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(2940),
                            DefaultValue = "false",
                            FeatureKey = "white_label",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "White Label"
                        },
                        new
                        {
                            Id = new Guid("f4f8385d-c95f-4607-9739-5462478ad5b4"),
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(2944),
                            DefaultValue = "false",
                            FeatureKey = "priority_support",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Priority Support"
                        },
                        new
                        {
                            Id = new Guid("f9826cdf-c4c0-4b1d-8467-b05100d2a558"),
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(2948),
                            DefaultValue = "false",
                            FeatureKey = "sso_integration",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "SSO Integration"
                        },
                        new
                        {
                            Id = new Guid("22e6b318-75a0-46fc-a174-44cd151534be"),
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(2950),
                            DefaultValue = "false",
                            FeatureKey = "advanced_security",
                            FeatureType = "Boolean",
                            IsActive = true,
                            IsSystemFeature = true,
                            Name = "Advanced Security"
                        });
                });

            modelBuilder.Entity("DRIYA.Platform.Models.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("boolean");

                    b.Property<string>("OverrideBy")
                        .HasColumnType("text");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("FeatureId", "TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BillingPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BillingPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StripeInvoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ItemType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.LicensePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowTrial")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemPlan")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxApiCalls")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStorageGB")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TrialDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("LicensePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d8bfcea-2af6-49c7-8609-6c0364319662"),
                            AllowTrial = true,
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(1224),
                            Currency = "USD",
                            Description = "Basic plan for small teams",
                            IsActive = true,
                            IsSystemPlan = true,
                            MaxApiCalls = 1000,
                            MaxStorageGB = 10,
                            MaxUsers = 5,
                            MonthlyPrice = 29.99m,
                            Name = "Basic",
                            PlanCode = "basic",
                            TrialDays = 14,
                            YearlyPrice = 299.99m
                        },
                        new
                        {
                            Id = new Guid("b0697928-a655-4634-9444-af7bb30e93ec"),
                            AllowTrial = true,
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(1344),
                            Currency = "USD",
                            Description = "Professional plan for growing businesses",
                            IsActive = true,
                            IsSystemPlan = true,
                            MaxApiCalls = 10000,
                            MaxStorageGB = 100,
                            MaxUsers = 25,
                            MonthlyPrice = 99.99m,
                            Name = "Professional",
                            PlanCode = "pro",
                            TrialDays = 14,
                            YearlyPrice = 999.99m
                        },
                        new
                        {
                            Id = new Guid("fac4423c-a9d1-45b9-b24b-fc54b22f99ab"),
                            AllowTrial = true,
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 398, DateTimeKind.Utc).AddTicks(1347),
                            Currency = "USD",
                            Description = "Premium plan for enterprise customers",
                            IsActive = true,
                            IsSystemPlan = true,
                            MaxApiCalls = 100000,
                            MaxStorageGB = 1000,
                            MaxUsers = 100,
                            MonthlyPrice = 299.99m,
                            Name = "Premium",
                            PlanCode = "premium",
                            TrialDays = 14,
                            YearlyPrice = 2999.99m
                        });
                });

            modelBuilder.Entity("DRIYA.Platform.Models.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistory");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PaymentGateway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GatewayType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTestMode")
                        .HasColumnType("boolean");

                    b.Property<string>("MerchantId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SupportedCurrencies")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("SupportsBankTransfers")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsCreditCards")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsDigitalWallets")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsRecurringPayments")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TransactionFeeFixed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TransactionFeePercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("PaymentGateways");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GatewayFee")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("GatewayId")
                        .HasColumnType("uuid");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GatewayId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TenantId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemPermission")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb567f9e-e315-491b-8983-f9583a683da5"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(7380),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "User Management",
                            Resource = "User"
                        },
                        new
                        {
                            Id = new Guid("b2849410-f807-41ff-8b8f-e0cbb988e4a7"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8110),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "User Management",
                            Resource = "User"
                        },
                        new
                        {
                            Id = new Guid("297c1915-d7e4-4397-b70a-c3f948c3db67"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8113),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "User Management",
                            Resource = "User"
                        },
                        new
                        {
                            Id = new Guid("793fe705-e661-4a29-a057-0be129eebf44"),
                            Action = "Delete",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8124),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "User Management",
                            Resource = "User"
                        },
                        new
                        {
                            Id = new Guid("dfd542df-f9f6-4679-90f9-2754826d0bb7"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8126),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Tenant Management",
                            Resource = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("067e60ea-944f-4a56-9a7e-db3ba16e47b7"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8129),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Tenant Management",
                            Resource = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("a90dbeb9-3345-40b2-9524-83ab900eff3e"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8131),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Tenant Management",
                            Resource = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("d0682628-ff0d-4b24-b816-78c314372441"),
                            Action = "Delete",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8135),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Tenant Management",
                            Resource = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("493ff431-fcc8-481c-a151-34b6d42ffe30"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8137),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Billing Management",
                            Resource = "Billing"
                        },
                        new
                        {
                            Id = new Guid("d8825212-6974-43a1-b44b-64028af730f9"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8164),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Billing Management",
                            Resource = "Billing"
                        },
                        new
                        {
                            Id = new Guid("0a5d183d-6b57-4785-bb2d-de206012885c"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8167),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Billing Management",
                            Resource = "Billing"
                        },
                        new
                        {
                            Id = new Guid("526d529a-56b9-40dc-8dba-f2bfa5d4ec77"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8174),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Feature Management",
                            Resource = "Feature"
                        },
                        new
                        {
                            Id = new Guid("03880b31-77c8-4f76-8e7c-46e47928d3e5"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8176),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Feature Management",
                            Resource = "Feature"
                        },
                        new
                        {
                            Id = new Guid("a578fdc6-2437-48a9-ac9a-81661bb76423"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8177),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "Feature Management",
                            Resource = "Feature"
                        },
                        new
                        {
                            Id = new Guid("9571f4ba-0235-4d10-9983-9232494639a5"),
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8179),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "API Key Management",
                            Resource = "ApiKey"
                        },
                        new
                        {
                            Id = new Guid("1cfaba35-bc9c-4755-b372-f80ed2b350fe"),
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8182),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "API Key Management",
                            Resource = "ApiKey"
                        },
                        new
                        {
                            Id = new Guid("cdb88d71-3e60-4b47-9f38-821a6c5fa9a3"),
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8184),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "API Key Management",
                            Resource = "ApiKey"
                        },
                        new
                        {
                            Id = new Guid("33272ab9-3b09-4f7b-a6c6-0ca98d1dce81"),
                            Action = "Delete",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(8210),
                            IsActive = true,
                            IsSystemPermission = true,
                            Name = "API Key Management",
                            Resource = "ApiKey"
                        });
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("Limit")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanFeatures");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentRoleId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("ParentRoleId");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(2108),
                            Description = "Global system administrator with full access",
                            HierarchyLevel = 0,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "GlobalAdmin",
                            NormalizedName = "GLOBALADMIN"
                        },
                        new
                        {
                            Id = "2",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(2308),
                            Description = "Tenant administrator with full tenant access",
                            HierarchyLevel = 1,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "TenantAdmin",
                            NormalizedName = "TENANTADMIN"
                        },
                        new
                        {
                            Id = "3",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(2329),
                            Description = "Manager with limited administrative access",
                            HierarchyLevel = 2,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "4",
                            CreatedAt = new DateTime(2025, 8, 24, 3, 49, 20, 397, DateTimeKind.Utc).AddTicks(2333),
                            Description = "Standard user with basic access",
                            HierarchyLevel = 3,
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("DRIYA.Platform.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrialActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactEmail");

                    b.HasIndex("CurrentPlanId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.TenantDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionString")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ConnectionTimeout")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Port")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("UseSSL")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantDatabases");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKey", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("ApiKeys")
                        .HasForeignKey("TenantId");

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKeyUsage", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApiKey", "ApiKey")
                        .WithMany("UsageHistory")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApplicationUser", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.FeatureFlag", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Feature", "Feature")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("TenantId");

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Feature");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Invoice", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.LicensePlan", "Plan")
                        .WithMany("Invoices")
                        .HasForeignKey("PlanId");

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("Invoices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.InvoiceItem", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.LoginHistory", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany("LoginHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PaymentTransaction", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.PaymentGateway", "Gateway")
                        .WithMany("Transactions")
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DRIYA.Platform.Models.Invoice", "Invoice")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gateway");

                    b.Navigation("Invoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PlanFeature", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Feature", "Feature")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.LicensePlan", "Plan")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Role", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Role", "ParentRole")
                        .WithMany("ChildRoles")
                        .HasForeignKey("ParentRoleId");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.RolePermission", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Tenant", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.LicensePlan", "CurrentPlan")
                        .WithMany("Tenants")
                        .HasForeignKey("CurrentPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentPlan");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.TenantDatabase", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany("TenantDatabases")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.UserPermission", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.UserRole", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DRIYA.Platform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApiKey", b =>
                {
                    b.Navigation("UsageHistory");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.ApplicationUser", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("LoginHistory");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Feature", b =>
                {
                    b.Navigation("FeatureFlags");

                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.LicensePlan", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("PlanFeatures");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.PaymentGateway", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Role", b =>
                {
                    b.Navigation("ChildRoles");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DRIYA.Platform.Models.Tenant", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("FeatureFlags");

                    b.Navigation("Invoices");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("TenantDatabases");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
